
title: Great Ouse Ways
email: grow@greatouseways.info
description: >- # this means to ignore newlines until "baseurl:"
  A guide to exploring the Great Ouse
baseurl: "" 
url: "" 
twitter_username: greatouseways
bsky_username: greatouseways

theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

exclude:
    - docs/

collections:
  walks:
    output: true
    title: Walks
    permalink: /:collection/:name.html
  places:
    output: true
    title: Places
    permalink: /:collection/:name.html
